### ISSUE TITLE
[Crash][1.9.3.3-BETA]: Unloading a bukkit world 

### ISSUE THREAD

**Issue by edwinPn** [Isolonice/IsoWorlds#1]
- Explainations
When some worlds unloads after the process of inactivity check, a crash happens.

- Can it be reproduced ?
Yes by unloading the same world

- Version
1.9.3.3-BETA (Bukkit)

- Server
Thermos

- IG logs
https://pastebin.com/Y89kJwic

- Crash report
https://pastebin.com/aazyfDtz

**Comment by wolfnether** [comment]
why unload and deleting asynchronously bukkit world ?
this is the cause of your bug i think

**Comment by edwinPn** [comment]
Well thanks ! A new version is on test with your fix
